BUILD: Create BINDIR if missing for QF_C target
as in QF_Cm/Makefile. Before this changeset, building on Linux x86_64
aborts with

    Fatal error: can't create linux/qep.o: No such file or directory